name: Solar system App

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"
jobs:

  code-coverage:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4.4.0
        with:
            node-version: 20

      - name: install npm
        run: npm install

      - name: unit testing
        continue-on-error: true
        run: npm run coverage
      
      - uses: actions/upload-artifact@v4
        if: failure() || success()
        with:
            name: code-coverage-result
            path: coverage
            retention-days: 5

  unit-testing:
    name: My Unit testing
    strategy:
      matrix:
        node_version: [18, 22]
        operating_system: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout
        uses: actions/checkout/@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: install npm
        run: npm i

      - name: run unit tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: failure() || success()
        with:
            name: moch-test-result
            path: test-results.xml